/-
Copyright (c) 2026 CompPoly Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Derek Sorensen
-/
module

public import CompPoly.Fields.KoalaBear.Ext5.QuinticCertData
public import CompPoly.Fields.KoalaBear.Basic
public import Mathlib.Tactic.ComputeDegree
public import Mathlib.Tactic.NormNum.Prime

/-!
# Irreducibility of `X^5 + X^2 - 1` over KoalaBear

The quintic `X^5 + X^2 - 1` is irreducible over `KoalaBear.Field`, proved by Rabin's test at
prime degree (`CompPoly.RabinCert.irreducible_of_rabin_prime_degree_of_card`). No degree-5
*binomial* does the job: `gcd(5, p - 1) = 1`, so `x ↦ x^5` is a bijection on KoalaBear and every
`X^5 - W` has a root. This non-binomial quintic is the defining polynomial of the degree-5
extension in `CompPoly/Fields/KoalaBear/Ext5.lean`.

The two Rabin conditions — `f ∣ X^(p^5) - X` and `IsCoprime f (X^p - X)` — are discharged by
kernel-checked certificates from `CompPoly/Fields/KoalaBear/Ext5/QuinticCertData.lean`
(generated by `scripts/gen_rabin_certificate.py`): a 211-step square-and-multiply chain for the
trace condition, a 37-step chain plus a Bézout identity for coprimality. Each chain is verified
by a single kernel reduction of `CompPoly.RabinCert.runChain` — `Nat` arithmetic only, no
`native_decide`.

## Main statements

* `KoalaBear.quinticPoly`: the polynomial `X^5 + X^2 - 1` over `KoalaBear.Field`.
* `KoalaBear.quinticPoly_irreducible`, and the `Fact` instance consumed by
  `CompPoly.Extension.Ext.instField`.
-/

@[expose] public section

namespace KoalaBear

open Polynomial CompPoly.RabinCert

/-- The defining quintic `X^5 + X^2 - 1` of the degree-5 KoalaBear extension. -/
noncomputable def quinticPoly : Polynomial Field := X ^ 5 + X ^ 2 - C 1

/-- The quintic's little-endian `ℕ`-coefficient encoding, with `-1` represented as `p - 1`. -/
def quinticL : List ℕ := [2130706432, 0, 1, 0, 0, 1]

/-- `p - 1` casts to `-1`. -/
private theorem cast_p_sub_one : ((2130706432 : ℕ) : Field) = -1 := by
  refine eq_neg_of_add_eq_zero_left ?_
  have h : ((2130706432 : ℕ) : Field) + 1 = ((2130706433 : ℕ) : Field) := by
    rw [← Nat.cast_one, ← Nat.cast_add]
  have hsize : (2130706433 : ℕ) = fieldSize := by norm_num [fieldSize]
  rw [h, hsize, ZMod.natCast_self]

/-- The `ℕ`-coefficient encoding denotes the quintic. -/
theorem toPoly_quinticL : toPoly fieldSize quinticL = quinticPoly := by
  show toPoly fieldSize [2130706432, 0, 1, 0, 0, 1] = quinticPoly
  rw [quinticPoly, toPoly_cons, toPoly_cons, toPoly_cons, toPoly_cons, toPoly_cons, toPoly_cons,
    toPoly_nil, cast_p_sub_one, Nat.cast_zero, Nat.cast_one, map_zero, map_one, map_neg, map_one]
  ring

theorem quinticPoly_natDegree : quinticPoly.natDegree = 5 := by
  rw [quinticPoly]
  compute_degree!

theorem quinticPoly_ne_zero : quinticPoly ≠ 0 := by
  intro h
  have h5 := quinticPoly_natDegree
  rw [h, natDegree_zero] at h5
  exact absurd h5 (by norm_num)

/-!
### The kernel-checked certificates

Each theorem below is one kernel reduction: `runChain` re-verifies every step of the generated
chain (`cur² = q·f + r`, coefficientwise mod `p`), and `chainExp` recomputes the exponent the
chain reaches. `eqModP` checks the Bézout identity for coprimality.
-/

set_option maxRecDepth 40000 in
/-- The 211-step chain for `X^(p^5) mod f` verifies and ends at the residue `X`. -/
theorem quintic_trace_chain :
    runChain fieldSize quinticL [0, 1] QuinticCert.traceSteps = some [0, 1] := by rfl

set_option maxRecDepth 40000 in
/-- The trace chain computes the exponent `p^5`. -/
theorem quintic_trace_exp : chainExp 1 QuinticCert.traceSteps = fieldSize ^ 5 := by rfl

set_option maxRecDepth 40000 in
/-- The 37-step chain for `X^p mod f` verifies and ends at the recorded residue. -/
theorem quintic_frob_chain :
    runChain fieldSize quinticL [0, 1] QuinticCert.frobSteps = some QuinticCert.rp := by rfl

set_option maxRecDepth 40000 in
/-- The Frobenius chain computes the exponent `p`. -/
theorem quintic_frob_exp : chainExp 1 QuinticCert.frobSteps = fieldSize := by rfl

/-- The recorded residue satisfies `rp = w + X`. -/
theorem quintic_w_check :
    eqModP fieldSize QuinticCert.rp (addNat QuinticCert.w [0, 1]) = true := by rfl

/-- The Bézout identity `u·f + v·w = 1` verifies. -/
theorem quintic_bezout_check :
    eqModP fieldSize
      (addNat (mulNat QuinticCert.u quinticL) (mulNat QuinticCert.v QuinticCert.w)) [1]
      = true := by rfl

/-- **`X^5 + X^2 - 1` is irreducible over KoalaBear**, by Rabin's test at prime degree with
kernel-checked certificates for both conditions. -/
theorem quinticPoly_irreducible : Irreducible quinticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_prime_degree_of_card hcard (by norm_num) quinticPoly_natDegree ?_ ?_
  · exact dvd_X_pow_sub_X_of_runChain toPoly_quinticL quinticPoly_ne_zero
      quintic_trace_chain quintic_trace_exp
  · exact isCoprime_X_pow_sub_X_of_runChain toPoly_quinticL quinticPoly_ne_zero
      quintic_frob_chain quintic_frob_exp quintic_w_check quintic_bezout_check

instance : Fact (Irreducible quinticPoly) := ⟨quinticPoly_irreducible⟩

end KoalaBear
